name: skRayFall
description: An addon for skript that adds Citizens support, EffectLib support and other features.
author: eyesniper2
website: https://sk.rayfall.net/
main: net.rayfall.eyesniper2.skrayfall.Core
version: 1.9.16
depend: [Skript]
softdepend: [Citizens, EffectLib, Votifier, ProtocolLib, Builder, HolographicDisplays, Sentry, CrackShot, CoreProtect, BossBarAPI]
commands:
  skrayfall:
    description: Base for all skRayFall commands.
    aliases: [rayfall, skrf]
    usage: /skrayfall <reload>
